import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import { CategoriesWrapper } from "@/context/category-name";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Poppins } from 'next/font/google';
import { Alexandria } from 'next/font/google';
import "./globals.css";


const poppins = Poppins({
  weight: ['100', '400', '500', '700'],
  subsets: ['latin'],
});
const alexandria = Alexandria({
  weight: ['100', '400', '500', '700'],
  subsets: ['arabic'],
});

export const metadata = {
  title: "Test",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"}>
      <body
        className={` ${locale == 'en' ? poppins.className : alexandria.className} bg-body  antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <CategoriesWrapper>
            <Navbar />
            {children}
            <Footer />
          </CategoriesWrapper>
        </NextIntlClientProvider>

      </body>
    </html>
  );
}
